### ISSUE TITLE
RSS Feed Not Working

### ISSUE THREAD

**Issue by jtv7** [Daltron/BigBoard#6]
it appears the news RSS feed doesn't work anymore.

**Comment by Daltron** [comment]
@jtv7 Thanks for bringing this to my attention. Looks like when I added https support, there was an accident that caused another `s` to be placed after the`https` in the url causing it to be `httpss`, thus causing the feed to not properly be serialized. This is now fixed in the latest release. Simply run `pod update BigBoard` and you should be good to go!

Thanks! 😃
